spring:
  main:
    web-application-type: none
  application:
    name: kotlin-batch-demo
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:springbatch;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  batch:
    job:
#      enabled: false
      names: ${job.names:NONE}